repos:
-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        entry: make fmt
        language: python
    -   id: lint
        name: lint
        entry: make lint
        language: python